// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CreateFieldReq struct {
	FieldKey     string            `json:"fieldKey"`
	Label        string            `json:"label"`
	Type         string            `json:"type"`
	Required     bool              `json:"required"`
	OrderNum     int               `json:"orderNum"`
	Options      map[string]string `json:"options"`
	DefaultValue string            `json:"defaultValue"`
}

type CreateFormReq struct {
	FormKey     string `json:"formKey"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Layout      string `json:"layout"`
}

type EntryListResp struct {
	Total int64           `json:"total"`
	List  []FormEntryResp `json:"list"`
}

type FieldResp struct {
	Id       int64  `json:"id"`
	FieldKey string `json:"fieldKey"`
	Label    string `json:"label"`
	Type     string `json:"type"`
	Required bool   `json:"required"`
	OrderNum int    `json:"orderNum"`
}

type FormEntryResp struct {
	Id        int64  `json:"id"`
	FormId    int64  `json:"formId"`
	UserId    int64  `json:"userId"`
	Data      string `json:"data"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type FormResp struct {
	Id          int64  `json:"id"`
	FormKey     string `json:"formKey"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Layout      string `json:"layout"`
	CreatedAt   string `json:"createdAt"`
}

type GetFormByIdReq struct {
	Id int64 `json:"id" path:"id"`
}

type ListEntriesReq struct {
	Id int64 `json:"id" path:"id"`
}

type ListFieldsReq struct {
	Id int64 `json:"id" path:"id"`
}

type ListFormsReq struct {
}

type SubmitEntryReq struct {
	Data string `json:"data"`
}
